# Generated by Django 4.2.6 on 2023-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_status',
            field=models.BooleanField(default=False),
        ),
    ]
