# Generated by Django 4.2.6 on 2023-10-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open'), ('Waiting for Response', 'Waiting for Response'), ('Waiting for Handling', 'Waiting for Handling')], max_length=20)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
