apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: first-app
spec:
  selector:
    app: frontend  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: first-app
spec:
  selector:
    app: backend  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
