# Generated by Django 4.2.4 on 2023-10-19 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(related_name='parents', to='people.people'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=999999)]),
        ),
    ]
    def round_salary(app):
        model = app.get_model('people','Parent')

        for parent in model.objects.all():
            parent.salary = int(float(parent.salary))
            parent.save()
